# Site settings
title: Scott Harris Blog
email: spharris@gmail.com
description: > 
  A blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://spharris.github.io" # the base hostname & protocol for your site
# url: http://localhost:4000
github_username:  spharris
