# Site settings
title: Scott's Blog
email: spharris@gmail.com
description: > 
  Where I try to become a better programmer by writing about it rather than
  actually doing it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://spharris.github.io" # the base hostname & protocol for your site
github_username:  spharris